// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juhvjvqamzylvtumhkde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1aHZqdnFhbXp5bHZ0dW1oa2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDUwMzMsImV4cCI6MjA2NzIyMTAzM30.fr058tgCEbhBSIQDuNrvXgvwGiUK-dGLYej7hl-RMyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});